version: '1.0'
services:
  graphqldemo:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'