spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: pass
    url: jdbc:postgresql://host.docker.internal:5432/blog
  sql:
    init:
      mode: always
  graphql:
    graphiql:
      enabled: true

# default address for querying GUI: localhost:8080/graphiql
graphql:
  servlet:
    mapping: /graphql
  tools:
    schema-location-pattern: "classpath*:graphql/**/*/graphqls"
