apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphqlapp
  labels:
    app: graphqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      # is a common practice to use app key (can be whatever)
      app: graphqlapp
  # blueprint / configuration of the pod for this deployment
  template:
    metadata:
      labels:
        app: graphqlapp
    spec:
      containers:
        - name: graphqldemo
#          image: lsalmeida/graphqldemo:latest
          image: graphqlapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: psql-user
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-user
          - name: psql-password
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: psql-password
          - name: db-url
            valueFrom:
              configMapKeyRef:
                name: psql-config
                key: psql-url
---
apiVersion: v1
kind: Service
metadata:
  name: graphqlapp-service
spec:
  type: NodePort # External service type (require nodePort)
  selector: # should match the labels in the pod that will be called with this service
    app: graphqlapp
  ports: # in this case psql-service will forward any request made to 27017(port) to 27017(targetPort) container/pod port.
    - protocol: TCP
      port: 8080
      targetPort: 8080 # port of the pods that belong to the service
      nodePort: 30100 # external port